### ISSUE TITLE
Loading over https doesn't work

### ISSUE THREAD

**Issue by RomanGotsiy** [BigstickCarpet/json-schema-ref-parser#10]
`https` protocol is ignored and specs are always loaded over `http`

Check out the attached picture. Despite spec url starts from `https://` Chrome Debugger Network tab says that spec was loaded over `http`:

![http://i.imgur.com/42T6CLI.png](http://i.imgur.com/42T6CLI.png)

I've done some research and found out that the issue is caused by this issue: https://github.com/substack/https-browserify/issues/6

So I believe to fix this issue you just need to update `browserify` version to v13 in this and maybe in [BigstickCarpet/simplifyify](https://github.com/BigstickCarpet/simplifyify) package

**Comment by BigstickCarpet** [comment]
:+1: Thanks for the heads-up.  I'll update the dependencies in the next release

**Comment by miccom86** [comment]
Hello all

I am using a swagger-parser in order to validate a special json file. I have the following error:

.....................................................................................
Swagger schema validation failed. 
  Additional properties not allowed: usbMemoryTotalBytes,flashMemoryAvailBytes,model,powerSource,firmwareVersionMain,boardVersion,supplyVoltage,serialNumber,id,runTime,vendor,boardVoltage,frequencySource,flashMemoryTotalBytes,boardTemperature,CPUFrequency,ramSize,hardwareVersion,usbMemoryAvailBytes,externalAntennaStatus at #/definitions//receiver/information//properties/information
 
JSON_OBJECT_VALIDATION_FAILED

Error: Swagger schema validation failed. 
  Additional properties not allowed: usbMemoryTotalBytes,flashMemoryAvailBytes,model,powerSource,firmwareVersionMain,boardVersion,supplyVoltage,serialNumber,id,runTime,vendor,boardVoltage,frequencySource,flashMemoryTotalBytes,boardTemperature,CPUFrequency,ramSize,hardwareVersion,usbMemoryAvailBytes,externalAntennaStatus at #/definitions//receiver/information//properties/information
 
JSON_OBJECT_VALIDATION_FAILED
    at http://127.0.0.1:8080/www/js/bundle.min.js:11:318
    at http://127.0.0.1:8080/www/js/bundle.min.js:50:316 

SyntaxError: Swagger schema validation failed. 
  Additional properties not allowed: usbMemoryTotalBytes,flashMemoryAvailBytes,model,powerSource,firmwareVersionMain,boardVersion,supplyVoltage,serialNumber,id,runTime,vendor,boardVoltage,frequencySource,flashMemoryTotalBytes,boardTemperature,CPUFrequency,ramSize,hardwareVersion,usbMemoryAvailBytes,externalAntennaStatus at #/definitions//receiver/information//properties/information
 
JSON_OBJECT_VALIDATION_FAILED
    at Function.syntax (http://127.0.0.1:8080/dist/swagger-parser.min.js:284:318)
    at validateSchema (http://127.0.0.1:8080/dist/swagger-parser.min.js:20:254)
    at http://127.0.0.1:8080/dist/swagger-parser.min.js:8:1921 

z-schema validation error: JSON_OBJECT_VALIDATION_FAILED
    at ZSchema.getLastError (http://127.0.0.1:8080/dist/swagger-parser.min.js:2047:3479)
    at validateSchema (http://127.0.0.1:8080/dist/swagger-parser.min.js:20:158)
    at http://127.0.0.1:8080/dist/swagger-parser.min.js:8:1921

............................................................
The swagger validate give me those error when it tries to validate the following json lines:
..............................................................................
   "definitions": {
        "/receiver/information/": {
            "description": "Receiver Information Resources",
            "x-permission": ["GET"],
            "properties": {
                "information": {
                    "externalAntennaStatus" :{
                        "title":"#/basic/Receiver/Information/externalAntennaStatus"
                    },
                    "usbMemoryAvailBytes" :{
                        "title":"#/basic/Receiver/Information/usbMemoryAvailBytes"
                    },
                    "hardwareVersion" : {
                        "title":"#/basic/Receiver/Information/hardwareVersion"
                    },

        . . .. . . . .. . . . .. . . .
.............................................................
Unfortunately I have to keep the json file as is.  I have to add a special rule in order to "validate" my special json file, without put the x-property in json file.

Where is the best place to add this special rule into swagger-parser ? How can it could be ?

I am working in local.


Thanks in advance for your help
Francesco

**Comment by BigstickCarpet** [comment]
@RomanGotsiy - I just released a new version of JSON-Schema-$Ref-Parser that was built with an updated version of Browserify, which uses `stream-http` instead of `http-browserify`.  So this issue should be fixed now.  Can you give it a try and let me know?

I'm going to optimistically close this issue.  But feel free to re-open it if it turns out that I've been too hasty :)

**Comment by RomanGotsiy** [comment]
@BigstickCarpet I'm using `json-schema-ref-parser` only as a part of `swagger-parser`. But I believe that the new version of `json-schema-ref-parser` is not compatible with the old `swagger-parser`. So I can't check it before https://github.com/BigstickCarpet/swagger-parser/issues/30 is closed :) Am I right?
I'm sure the issue is fixed now. Thanks!

**Comment by BigstickCarpet** [comment]
Ah, ok.  Well I've started working on a new build of Swagger Parser with the updated version of JSON Schema $Ref Parser... so expect that soon
