### ISSUE TITLE
Bundle replaces duplicate $refs with relative pointers

### ISSUE THREAD

**Issue by philosowaffle** [BigstickCarpet/json-schema-ref-parser#101]
First and foremost, this may be a non-issue, I just wanted to confirm the behavior was intended and verify that I am using the library correctly.  This also may not be the correct repo for this issue.

I had an [issue](https://github.com/philosowaffle/vs-openapi-designer/issues/12) logged where a user was getting errors in their swagger doc after using multiple $refs to the same file.  [Example Schema](https://github.com/philosowaffle/vs-openapi-designer/tree/issue/issue_12/test/issue_12)

The following test code demonstrates the issue using the linked schema:
```java
const refParser = require('json-schema-ref-parser')
const path = require('path');

var source = path.join(__dirname, '/schema/petstore.yaml');

refParser.bundle(source, (err, schema) => {
    if (err) {
        console.error('ERROR:', err);
    }
    else {
       // at this point swagger editor claims the schema is invalid
        console.log('SUCCESS:', JSON.stringify(schema, null, 2)); 
        console.log("DEREFERENCE");

        refParser.dereference(schema, (err, drSchema) => {
            if (err) {
                console.error('ERROR:', err);
            }
            else {
               // after a dereference, swagger editor says schema is valid
                console.log('SUCCESS:', JSON.stringify(drSchema, null, 2)); 
            }
        });
    }
});
```

An initial call to bundle creates a schema that uses local json pointers for the duplicate references.  However, this throws errors when copy/pasted into the official [Swagger Editor](https://editor.swagger.io/).  I noticed that this same bundled schema does not yield any errors when plugged into your [Swagger Validator Demo](http://bigstickcarpet.com/swagger-parser/www/index.html#).

After reading through this [issue](https://github.com/BigstickCarpet/swagger-parser/issues/80) I determined that you must be calling `dereference` before doing the validation.  When I add a follow up call to dereference, as seen in the test above, the relative json pointers are dereferenced and swagger editor is happy again.

1. Is this intended behavior?
2. Is calling `bundle` followed by `dereference` a suitable workaround, or should I be doing something else in entirely?

**Comment by BigstickCarpet** [comment]
Hi @philosowaffle.  Welcome to the wonderful world of incompatible Swagger tooling!  😄

Unfortunately, as you've discovered, not all Swagger & OpenAPI tools are compatible.  Many of them don't fully support the spec, and there are a few areas where the spec is unclear so different tooling authors have implemented it differently.

Swagger Editor is a fantastic tool, but its `$ref` support is somewhat lacking.  This has led to [other](https://github.com/BigstickCarpet/json-schema-ref-parser/issues/44) [issues](https://github.com/swagger-api/swagger-editor/issues/1430) [in the](https://github.com/BigstickCarpet/swagger-parser/issues/82) [past](https://github.com/BigstickCarpet/swagger-parser/issues/47).  For now, the only workaround is to use `dereference()` rather than `bundle()`, since `dereference()` produces a file without any `$refs`, so it's guaranteed to work in Swagger Editor.

**Comment by philosowaffle** [comment]
Thanks!
