### ISSUE TITLE
Cannot find name 'Buffer' when running in Browser

### ISSUE THREAD

**Issue by scottseeker** [BigstickCarpet/json-schema-ref-parser#61]
I assume this is look for the node type 'Buffer'?  Including type: ['node'] in my tsconfig causes too many other conflicts.  Is there a way around this?

**Comment by BigstickCarpet** [comment]
Please see the [changelog for version 4.0.0](https://github.com/BigstickCarpet/json-schema-ref-parser/blob/master/CHANGELOG.md#v400-2017-10-13), which includes links to polyfill libraries that you can use.  They were previously included in json-schema-ref-parser, but they've been removed to reduce the size of the library, since most browsers have native support now
