### ISSUE TITLE
parsers/resolvers get partial file URL for json-pointer refs

### ISSUE THREAD

**Issue by eliranmal** [BigstickCarpet/json-schema-ref-parser#63]
## description

when a schema definition includes `$ref`s with (non-relative) json-pointer values, any parsers/resolvers hook functions (namely, `read()`, `parse()`, `canRead()` and `canParse()`) are called with a file info object that has a partial URL.

_"partial URL"_ here refers to the original json-pointer URI, stripped of its anchor segment, for example, `http://mydomain/schema#/inner` would become `http://mydomain/schema`.

this behavior is the same for both `bundle()` and `dereference()` (other API methods had not been tested).

it makes handling of such json-pointer `$ref`s harder when writing custom resolvers/parsers (my use case is returning 'mock' or 'placeholder' schemas for some user defined `$ref` matches in a generated bundle).

## steps to reproduce

1. create a schema definition with a json-pointer `$ref`, e.g.:
   
   ```js
   const mySchema = {
     "$ref": "http://mydomain.com/schema#/inner"
   };
   ```

1. implement any of the custom resolvers/parsers hook functions, and test the `file.url` value:
   
   ```js
   parser.bundle(mySchema, {
     resolve: {
       myResolver: {
         order: 1,
         canRead: (file) => {
           console.log(file.url); // -> http://mydomain.com/schema
           return true;
         },
       },
     },
   });
   ```

see a runnable [demo on runkit][1].

## expected result

the file info object's `url` field should hold the `$ref` value as found in the original schema definition.

## actual result

the file info object's `url` field hold a partial value, in case of json-pointer URI values - the anchor segment is stripped out.

## workarounds

- ~~i think one can retrieve the last value of `parser.$refs.paths()` and have the full URL for a specific invocation of `parse()`, `canRead()` etc., but that's quite brittle - as the `$refs.paths()` API may change in future versions, and also not very pure (in a FP sense).
  i haven't tested this approach, though.~~ apparently, this approach doesn't work; `parser.$refs.paths()` returns the same stripped path.

[1]: https://runkit.com/eliranmal/json-schema-ref-parser---partial-file-url-bug

**Comment by eliranmal** [comment]
by the way, #47 seems interestingly aligned with my real use case. its resolution may render this issue redundant.

**Comment by BigstickCarpet** [comment]
Hi @eliranmal.  Sorry for taking so long to respond.

This behavior is by design.  When a [JSON Reference](https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03) (`$ref`) contains a hash character (`#`), the part before the hash indicates the resource that's being referenced, and the part after the hash is a [JSON Pointer](https://tools.ietf.org/html/rfc6901) that indicates a specific _part_ of that resource.  The "file info" object that's passed to the hook functions represents the _entire file_, not just a part of it, which is why the `url` property doesn't contain the hash portion.  The job of functions like `read()` and `parse()` is to read/parse the _entire_ resource.  After that, it's up to json-schema-ref-parser to crawl the parsed resource and find the specific part that the `$ref` points to.

**Comment by eliranmal** [comment]
@BigstickCarpet - i get it, i thought it would be easier for my use-case if the hash was passed as well.

i'll follow #47 and see if it matches my needs.

thanx :)
