### ISSUE TITLE
using in ng 6 fails to compile

### ISSUE THREAD

**Issue by geetee24** [BigstickCarpet/json-schema-ref-parser#87]
ng serve (ng6) results in 

ERROR in ./node_modules/json-schema-ref-parser/lib/resolvers/http.js
Module not found: Error: Can't resolve 'http' in '.....node_modules\json-schema-ref-parser\lib\resolvers'
ERROR in ./node_modules/json-schema-ref-parser/lib/resolvers/http.js
Module not found: Error: Can't resolve 'https' in '...\node_modules\json-schema-ref-parser\lib\resolvers'

Any ideas?   It does build in ng 5 just fine.

**Comment by BigstickCarpet** [comment]
It looks like you're trying to bundle the Node.js code rather than the browser code.  Make sure your bundler (webpack, or browserify, or whatever) is pointed at [`dist/ref-parser.js`](https://github.com/BigstickCarpet/json-schema-ref-parser/blob/master/dist/ref-parser.js) rather than [`lib/index.js`](https://github.com/BigstickCarpet/json-schema-ref-parser/blob/master/lib/index.js)

**Comment by KensingtonTech** [comment]
FYI, for posterity, to implement @JamesMessinger's advise, do this in your root `tsconfig.json`:

```{
  ...
  "compilerOptions": {
    ...
    "paths": {
      "@apidevtools/json-schema-ref-parser": [
        "node_modules/json-schema-ref-parser/dist/ref-parser.min.js"
      ]
    }
  }
}```
