### ISSUE TITLE
Skip over certain $ref properties

### ISSUE THREAD

**Issue by chgennar** [BigstickCarpet/json-schema-ref-parser#88]
I would like to skip over certain $ref properties and leave them in their original state.  For example, I would prefer not to resolve any files that contain "examples" in their path.  I tried to set this up as follows, but it fails:

RefParser.bundle(argv.input, {
    resolve: {
        file: {
            canRead: (file) => {
                return !file.url.includes("examples");
            }
        }
    }
})

The failure has the message -> "message": "Unable to resolve $ref pointer ..."

**Comment by BigstickCarpet** [comment]
JSON Schema Ref Parser will throw an error if none of the resolvers are able to resolve a given `$ref`.  If you want to ignore certain references, then your custom resolver needs to return `true`, not `false`, that way JSON Schema Ref Parser will use your custom resolver instead of its default ones.  Then you need to implement [the `read()` method](https://github.com/BigstickCarpet/json-schema-ref-parser/blob/master/docs/plugins/resolvers.md#the-read-method)  and simply always return a dummy value, such as an empty JSON object (`"{}"`) or `null`

**Comment by malins** [comment]
Hello, I was trying to implement such a custom resolver. When returning just `"{}"` or `null`, the value in the schema is just replaced with `"{}"` or `null` (which is not what I want). When returning `"{\"$ref\":\"something.yaml\"}"` it is resolving this node in a loop, or it is causing some strange replacements to this value.

Do you have a working example for such a "certain refs ignoring resolver"?

Thank you!
